# Generated by Django 5.2.4 on 2025-07-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('number_of_pets', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExoticAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_of_origin', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('type_of_animal', models.CharField(max_length=100)),
                ('vaccinated', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exotic_animals', to='pets_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('vaccinated', models.BooleanField()),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='pets_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('vaccinated', models.BooleanField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='pets_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('vaccinated', models.BooleanField()),
                ('description', models.TextField()),
                ('species', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='pets_app.owner')),
            ],
        ),
    ]
